### PR TITLE
Dark theme for RESTMan

### PR DESCRIPTION
**Pull request by dbautistav**
This PR proposes a dark theme for RESTMan as described at issue #16. Check commits for details.

Preview: https://dbautistav.github.io/restman (toggle button at bottom-right corner).

@jsargiot: I have tested the extension in developer mode and everything works as expected. Your feedback and comments are very welcome.

### CODE REVIEW

**Comment by jsargiot** [comment]
thanks @dbautistav for the work!

I would like to split this PR in 3 though, one for the linting and modification of the resources path (and the license change), other for the version change (great work btw) and the last for the dark theme itself.

Let me know if you can split the change (sorry for the extra work).

FYI, I'm working on a style for the dark theme that doesn't involve just inverting color. I'll work on top of your work.

**Comment by dbautistav** [comment]
Very well @jsargiot, thanks for your feedback. I'll work on that.
I think we can add buttons (somewhere) for the three themes. What do you think about it?

As soon as I have each PR, I'll let you know and wait for your feedback.

**Comment by jsargiot** [comment]
thanks @dbautistav.

I was thinking of doing it kind of like this webpage: http://thetopfives.net/dashboard. There is a sun or a moon icon for light/dark themes. It's simple and doesn't take much of the attention.

**Comment by dbautistav** [comment]
Looks great for me. Thanks @jsargiot.

**Comment by jsargiot** [comment]
I've cherry-picked some of the commits (those that applied cleanly) of this PR. @dbautistav if you're still interested in the rest of the changes please update the PR or create a new one if it's easier for you. I've added a dark theme and will probably release it this weekend! Let me know what you think!

**Comment by dbautistav** [comment]
@jsargiot:

I've updated my local project with your changes, test your latest version locally and I really like the final result. That's what I was talking about! Thank you very much for your effort.

Also, I've fixed relative resources paths and create a new PR: https://github.com/jsargiot/restman/pull/19

Last but not least, let me tell you that recently I suggest restman to some colleagues who uses chrome and chromium as a lite option to postman. However currently it is not possible to install restman from chrome store (since its main target is opera browser) but only loading it as developer.
So I suggest you to add restman to chrome store in order to be easier to install it for chrome, chromium, vivaldi, et al. users. What do you think about it?

**Comment by jsargiot** [comment]
> I've updated my local project with your changes, test your latest version locally and I really like the final result. That's what I was talking about! Thank you very much for your effort.

I'm happy that you like it! 😃 

> Also, I've fixed relative resources paths and create a new PR: #19

Merged. Thanks! 👍 

> So I suggest you to add restman to chrome store in order to be easier to install it for chrome, chromium, vivaldi, et al. users. What do you think about it?

I think it's a great idea! It should work out-of-the-box with chrome, so no much work there. I'll publish next release (v0.6 soon to be released) both on opera and chrome stores! Thank you very much for spreading the love!! 😄

**Comment by dbautistav** [comment]
Thank you!  :+1:

**Pull request closed without merging**
